### PR TITLE
Update Arduino IDE setup in README.md 

### PR DESCRIPTION
**Pull request by Visruat**
Fixed all the typos, and added a few sentences.

kindly review the changes.

@dineshannayya

### CODE REVIEW

**Review by dineshannayya — APPROVED** [review]

**Comment by dineshannayya** [comment]
Thank Visruat, i have accepted the correction.

**Comment by Visruat** [comment]
the commit has not been merged @dineshannayya sir.

**Comment by dineshannayya** [comment]
can you cross check now

**Comment by Visruat** [comment]
Yessir looks good to go.

**Pull request merged**
